stages:
    - build
    - test_todo_api

build:
    image: golang:1.23-alpine
    stage: build
    before_script:
        - go mod download
    script:
        - go build -o todo

test_todo_api:
    image: golang:1.23-alpine