stages:
    - build
    - test_todo_api

variables:
    GO_VERSION: "1.23-alpine"

build:
    image: golang:${GO_VERSION}
    stage: build
    before_script:
        - go mod download
    script:
        - go build -o todo

test_todo_api:
    image: golang:{$GO_VERSION}
    stage: test_todo_api
    before_script: 
        - go mod download
    script:
        - go test 